// frontend/src/components/ForgotPassword.jsx
import React, { useState } from 'react';
import {
  Card,
  Button,
  Typography,
  Box,
  InputBase,
  styled
} from '@mui/material';
import { ArrowLeft } from 'lucide-react';
import { POST } from '../api';
import toast from 'react-hot-toast';
import DottedSpinner from './DottedSpinner.jsx';
import CryptoJS from 'crypto-js';
import config from '../config';
import { useNavigate } from 'react-router-dom';
// Custom styled components
const StyledCard = styled(Card)(({ theme }) => ({
  width: '100%',
  maxWidth: '440px',
  margin: '0 auto',
  boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
  borderRadius: '12px'
}));

const StyledButton = styled(Button)(({ theme }) => ({
  width: '100%',
  padding: '12px',
  borderRadius: '8px',
  textTransform: 'none',
  fontSize: '18px',
  backgroundColor: '#3b82f6',
  '&:hover': {
    backgroundColor: '#2563eb',
  }
}));

const StyledCodeInput = styled(InputBase)(({ theme }) => ({
  width: '48px',
  height: '48px',
  textAlign: 'center',
  fontSize: '22px',
  backgroundColor: '#f8fafc',
  borderRadius: '8px',
  border: '1px solid #e2e8f0',
  '&:focus': {
    border: '2px solid #3b82f6',
    backgroundColor: '#fff',
  },
  input: {
    textAlign: 'center',
  }
}));

const StyledInput = styled(InputBase)(({ theme }) => ({
  width: '100%',
  padding: '12px 16px',
  backgroundColor: '#f8fafc',
  borderRadius: '8px',
  border: '1px solid #e2e8f0',
  marginBottom: '12px',
  transition: 'all 0.2s',
  '&:focus-within': {
    border: '2px solid #3b82f6',
    backgroundColor: '#fff',
  }
}));

const ForgotPassword = ({ setShowModal }) => {
  const [currentStep, setCurrentStep] = useState(1);
  const [email, setEmail] = useState('');
  const [Code, setCode] = useState(['', '', '', '', '', '']);
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleEmailSubmit = async (e) => {
    e.preventDefault();
    setLoading(true); // Start loading

    try {
      const result = await POST('/api/sendemail/forgotpassword', { email, CheckUserExist: true });

      if (result.data?.success) {
        toast.success(result.data?.message);
        setCurrentStep(2);
      } else if (result.data?.caught) {
        navigate('/login'); return;
        // toast.error(result.data?.message);
      } else {
        toast.error(result.data?.message);
      }
    } catch (error) {
      toast.error('Something went wrong.');
    } finally {
      setLoading(false); // Stop loading once the API call is complete
    }
  };

  const handleCodeSubmit = async (e) => {
    e.preventDefault();
    const response = await POST('/api/sendemail/forgotpassword/verifycode', { email: email, code: Code });

    if (response.data?.success) {
      toast.success(response.data?.message);
      setCurrentStep(3);
    } else if (response.data?.caught) {
      // toast.error(response.data?.message);
      navigate('/login'); return;
    } else {
      toast.error(response.data?.message);
    }
  };

  const handlePasswordSubmit = async (e) => {
    e.preventDefault();
    if (newPassword !== confirmPassword) {
      toast.error('Passwords do not match');
      return;
    }

    const encryptedPassword = CryptoJS.AES.encrypt(newPassword, config.PWD_SECRET).toString();
    const response = await POST('/api/sendemail/forgotpassword/resetpassword', { email: email, password: encryptedPassword });

    if (response.data?.success) {
      toast.success(response.data?.message);
      setShowModal(false);
    } else if (response.data?.caught) {
      navigate('/login'); return;
      // toast.error(response.data?.message);
    } else {
      toast.error(response.data?.message);
    }
  };



  const handleCodeChange = (index, value) => {
    if (!/^\d$/.test(value)) return; // Only allow digits

    const newCode = [...Code];
    newCode[index] = value;
    setCode(newCode);

    // Auto-focus the next input field if not at the last input
    if (index < 5 && value !== '') {
      const nextInput = document.getElementById(`Code-${index + 1}`);
      if (nextInput) nextInput.focus();
    }
  };

  const handleKeyDown = (index, event) => {
    if (event.key === 'Backspace') {
      event.preventDefault(); // Prevent default backspace behavior

      const newCode = [...Code];

      if (newCode[index] === '') {
        // If current box is empty and we press backspace, clear previous box and move there
        if (index > 0) {
          newCode[index - 1] = '';
          setCode(newCode);
          const prevInput = document.getElementById(`Code-${index - 1}`);
          if (prevInput) prevInput.focus();
        }
      } else {
        // If current box has a number, just clear it and stay there
        newCode[index] = '';
        setCode(newCode);
      }
    }
  };




  const renderStep = () => {
    switch (currentStep) {
      case 1:
        return (
          <Box sx={{ p: 0, marginTop: "-20px" }}>
            <Box sx={{ mb: 1 }}>
              <Button
                sx={{
                  minWidth: 'auto',
                  color: 'text.primary',
                  '&:hover': { backgroundColor: 'transparent' }
                }}
                onClick={() => setCurrentStep(currentStep - 1)}
              />
              <Typography variant="body2" color="text.secondary">
                Enter your registered email address to receive a verification code.
              </Typography>
            </Box>

            <form onSubmit={handleEmailSubmit}>
              <Box sx={{ mb: 2 }}>
                <StyledInput
                  type="email"
                  placeholder="Enter your email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  fullWidth
                  required
                />
              </Box>
              <StyledButton variant="contained" type="submit" disabled={loading}>
                {loading ? <DottedSpinner /> : 'Reset Password'}
              </StyledButton>
            </form>
          </Box>
        );

      case 2:
        return (
          <Box sx={{ p: 3 }}>
            <Box sx={{ mb: 3 }}>
              <Button
                startIcon={<ArrowLeft />}
                sx={{
                  p: 0,
                  mb: 2,
                  minWidth: 'auto',
                  color: 'text.primary',
                  '&:hover': { backgroundColor: 'transparent' }
                }}
                onClick={() => setCurrentStep(currentStep - 1)}
              />
              <Typography variant="h5" sx={{ mb: 1, fontWeight: 600 }}>
                Check your email
              </Typography>
              <Typography variant="body2" color="text.secondary">
                We sent a code to {email}
              </Typography>
            </Box>

            <form onSubmit={handleCodeSubmit}>
              <Box
                sx={{
                  display: 'flex',
                  gap: 1,
                  justifyContent: 'center',
                  mb: 3
                }}
              >
                {Code.map((digit, index) => (
                  <StyledCodeInput
                    key={index}
                    id={`Code-${index}`}
                    type="text"
                    maxLength={1}
                    value={digit}
                    onChange={(e) => handleCodeChange(index, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(index, e)}
                    required
                  />
                ))}
              </Box>
              <StyledButton variant="contained" type="submit">
                Verify Code
              </StyledButton>
            </form>
          </Box>
        );

      case 3:
        return (
          <Box sx={{ p: 3 }}>
            <Box sx={{ mb: 3 }}>
              <Button
                sx={{
                  p: 0,
                  mb: 2,
                  minWidth: 'auto',
                  color: 'text.primary',
                  '&:hover': { backgroundColor: 'transparent' }
                }}
                onClick={() => setCurrentStep(currentStep - 1)}
              />
              <Typography variant="h5" sx={{ mb: 1, fontWeight: 600 }}>
                Set a new password
              </Typography>
              <Typography variant="body2" color="text.secondary">
                Please enter your new password
              </Typography>
            </Box>

            <form onSubmit={handlePasswordSubmit}>
              <Box sx={{ mb: 3 }}>
                <StyledInput
                  type="password"
                  placeholder="Password"
                  value={newPassword}
                  onChange={(e) => setNewPassword(e.target.value)}
                  fullWidth
                  required
                />
                <StyledInput
                  type="password"
                  placeholder="Confirm Password"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  fullWidth
                  required
                />
              </Box>
              <StyledButton variant="contained" type="submit">
                Update Password
              </StyledButton>
            </form>
          </Box>
        );

      default:
        return null;
    }
  };

  return (
    <StyledCard>
      {renderStep()}
    </StyledCard>
  );
};

export default ForgotPassword;

// frontend_angular/src/app/components/forgot-password/forgot-password.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBarModule, MatSnackBar } from '@angular/material/snack-bar';
import * as CryptoJS from 'crypto-js';
import { ApiService } from '../../services/api.service';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-forgot-password',
  standalone: true,
  imports: [CommonModule, FormsModule, MatIconModule, MatProgressSpinnerModule, MatSnackBarModule],
  templateUrl: './forgot-password.component.html',
  styleUrls: ['./forgot-password.component.scss']
})
export class ForgotPasswordComponent {
  @Output() closed = new EventEmitter<void>();

  currentStep = 1;
  email = '';
  code: string[] = ['', '', '', '', '', ''];
  newPassword = '';
  confirmPassword = '';
  isLoading = false;
  errorMessage = '';
  successMessage = '';

  constructor(private api: ApiService, private snackBar: MatSnackBar) {}

  private toast(message: string): void {
    this.snackBar.open(message, '', { duration: 2500, horizontalPosition: 'center', verticalPosition: 'bottom' });
  }

  submitEmail(): void {
    if (!this.email) return;
    this.isLoading = true;
    this.errorMessage = '';

    this.api.post<any>('/api/sendemail/forgotpassword', {
      email: this.email,
      CheckUserExist: true
    }).subscribe({
      next: (res) => {
        this.isLoading = false;
        if (res?.success) {
          this.successMessage = res.message || 'Verification code sent!';
          this.toast(this.successMessage);
          this.currentStep = 2;
        } else {
          this.errorMessage = res?.message || 'Failed to send email.';
          this.toast(this.errorMessage);
        }
      },
      error: () => {
        this.isLoading = false;
        this.errorMessage = 'Something went wrong.';
      }
    });
  }

  onCodeInput(index: number, event: Event): void {
    const input = event.target as HTMLInputElement;
    const value = input.value;

    if (!/^\d$/.test(value)) {
      input.value = '';
      this.code[index] = '';
      return;
    }

    this.code[index] = value;

    if (index < 5 && value) {
      const next = document.getElementById(`forgot-code-${index + 1}`) as HTMLInputElement;
      if (next) next.focus();
    }
  }

  onCodeKeydown(index: number, event: KeyboardEvent): void {
    if (event.key === 'Backspace') {
      event.preventDefault();
      if (this.code[index] === '') {
        if (index > 0) {
          this.code[index - 1] = '';
          const prev = document.getElementById(`forgot-code-${index - 1}`) as HTMLInputElement;
          if (prev) {
            prev.value = '';
            prev.focus();
          }
        }
      } else {
        this.code[index] = '';
        (event.target as HTMLInputElement).value = '';
      }
    }
  }

  submitCode(): void {
    if (this.code.some(d => !d)) return;
    this.isLoading = true;
    this.errorMessage = '';

    this.api.post<any>('/api/sendemail/forgotpassword/verifycode', {
      email: this.email,
      code: this.code
    }).subscribe({
      next: (res) => {
        this.isLoading = false;
        if (res?.success) {
          this.successMessage = res.message || 'Code verified!';
          this.toast(this.successMessage);
          this.currentStep = 3;
        } else {
          this.errorMessage = res?.message || 'Invalid code.';
          this.toast(this.errorMessage);
        }
      },
      error: () => {
        this.isLoading = false;
        this.errorMessage = 'Something went wrong.';
      }
    });
  }

  submitNewPassword(): void {
    if (!this.newPassword || !this.confirmPassword) return;
    if (this.newPassword !== this.confirmPassword) {
      this.errorMessage = 'Passwords do not match.';
      this.toast(this.errorMessage);
      return;
    }

    this.isLoading = true;
    this.errorMessage = '';

    const encrypted = CryptoJS.AES.encrypt(this.newPassword, environment.PWD_SECRET).toString();

    this.api.post<any>('/api/sendemail/forgotpassword/resetpassword', {
      email: this.email,
      password: encrypted
    }).subscribe({
      next: (res) => {
        this.isLoading = false;
        if (res?.success) {
          this.successMessage = res.message || 'Password reset successfully!';
          this.toast(this.successMessage);
          setTimeout(() => this.closed.emit(), 1500);
        } else {
          this.errorMessage = res?.message || 'Failed to reset password.';
          this.toast(this.errorMessage);
        }
      },
      error: () => {
        this.isLoading = false;
        this.errorMessage = 'Something went wrong.';
      }
    });
  }

  onOverlayClick(event: Event): void {
    if ((event.target as HTMLElement).classList.contains('forgot-overlay')) {
      this.closed.emit();
    }
  }
}

<div class="forgot-overlay" (click)="onOverlayClick($event)">
  <div class="forgot-card" (click)="$event.stopPropagation()">
    <button class="close-btn" (click)="closed.emit()">
      <mat-icon>close</mat-icon>
    </button>

    <!-- Step 1: Enter Email -->
    @if (currentStep === 1) {
      <h2 class="step-title">Forgot Password</h2>
      <p class="step-subtitle">Enter your registered email address to receive a verification code.</p>

      @if (errorMessage) {
        <div class="error-msg">
          <mat-icon>error_outline</mat-icon>
          <span>{{ errorMessage }}</span>
        </div>
      }

      <form (ngSubmit)="submitEmail()">
        <div class="input-wrapper">
          <mat-icon class="field-icon">email</mat-icon>
          <input
            type="email"
            placeholder="Enter your email"
            [(ngModel)]="email"
            name="email"
            required
            class="custom-input"
          />
        </div>
        <button type="submit" class="submit-btn" [disabled]="isLoading || !email">
          @if (isLoading) {
            <mat-spinner diameter="22" class="btn-spinner"></mat-spinner>
          } @else {
            Reset Password
          }
        </button>
      </form>
    }

    <!-- Step 2: Enter Code -->
    @if (currentStep === 2) {
      <button class="back-btn" (click)="currentStep = 1; errorMessage = ''">
        <mat-icon>arrow_back</mat-icon>
      </button>
      <h2 class="step-title">Check your email</h2>
      <p class="step-subtitle">We sent a code to {{ email }}</p>

      @if (errorMessage) {
        <div class="error-msg">
          <mat-icon>error_outline</mat-icon>
          <span>{{ errorMessage }}</span>
        </div>
      }

      <form (ngSubmit)="submitCode()">
        <div class="code-inputs">
          @for (digit of code; track $index) {
            <input
              type="text"
              maxlength="1"
              class="code-input"
              [id]="'forgot-code-' + $index"
              [value]="digit"
              (input)="onCodeInput($index, $event)"
              (keydown)="onCodeKeydown($index, $event)"
            />
          }
        </div>
        <button type="submit" class="submit-btn" [disabled]="isLoading || code.some(d => !d)">
          @if (isLoading) {
            <mat-spinner diameter="22" class="btn-spinner"></mat-spinner>
          } @else {
            Verify Code
          }
        </button>
      </form>
    }

    <!-- Step 3: New Password -->
    @if (currentStep === 3) {
      <button class="back-btn" (click)="currentStep = 2; errorMessage = ''">
        <mat-icon>arrow_back</mat-icon>
      </button>
      <h2 class="step-title">Set a new password</h2>
      <p class="step-subtitle">Please enter your new password</p>

      @if (errorMessage) {
        <div class="error-msg">
          <mat-icon>error_outline</mat-icon>
          <span>{{ errorMessage }}</span>
        </div>
      }
      @if (successMessage) {
        <div class="success-msg">
          <mat-icon>check_circle</mat-icon>
          <span>{{ successMessage }}</span>
        </div>
      }

      <form (ngSubmit)="submitNewPassword()">
        <div class="input-wrapper">
          <mat-icon class="field-icon">key</mat-icon>
          <input
            type="password"
            placeholder="New password"
            [(ngModel)]="newPassword"
            name="newPassword"
            required
            class="custom-input"
          />
        </div>
        <div class="input-wrapper">
          <mat-icon class="field-icon">key</mat-icon>
          <input
            type="password"
            placeholder="Confirm password"
            [(ngModel)]="confirmPassword"
            name="confirmPassword"
            required
            class="custom-input"
          />
        </div>
        <button type="submit" class="submit-btn" [disabled]="isLoading || !newPassword || !confirmPassword">
          @if (isLoading) {
            <mat-spinner diameter="22" class="btn-spinner"></mat-spinner>
          } @else {
            Update Password
          }
        </button>
      </form>
    }
  </div>
</div>
