// frontend/src/components/ResetPassword.jsx
import React, { useState } from 'react';
import config from '../config';
import {
  Card,
  Box,
  Typography,
  InputBase,
  Button,
  InputAdornment,
  IconButton,
  styled
} from '@mui/material';
import { Eye, EyeOff, Check, X } from 'lucide-react';
import { POST } from '../api';
import toast from 'react-hot-toast';
import CryptoJS from 'crypto-js';
import { useNavigate } from 'react-router-dom';

// Styled components
const StyledCard = styled(Card)(({ theme }) => ({
  width: '100%',
  maxWidth: '440px',
  margin: '0 auto',
  padding: '32px',
  boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
  borderRadius: '12px',
  backgroundColor: '#ffffff'
}));

const StyledInput = styled(InputBase)(({ theme }) => ({
  width: '100%',
  backgroundColor: '#f8fafc',
  borderRadius: '8px',
  border: '1px solid #e2e8f0',
  transition: 'all 0.2s ease-in-out',
  marginBottom: '16px',
  '& .MuiInputBase-input': {
    padding: '14px 16px',
    fontSize: '17px',
    '&::placeholder': {
      color: '#94a3b8',
      opacity: 1,
    },
  },
  '&:hover': {
    borderColor: '#cbd5e1',
  },
  '&.Mui-focused': {
    borderColor: '#3b82f6',
    backgroundColor: '#ffffff',
    boxShadow: '0 0 0 4px rgb(59 130 246 / 0.1)',
  }
}));

const StyledButton = styled(Button)(({ theme }) => ({
  width: '100%',
  padding: '12px',
  marginTop: '8px',
  borderRadius: '8px',
  textTransform: 'none',
  fontSize: '18px',
  fontWeight: 500,
  backgroundColor: '#3b82f6',
  color: '#ffffff',
  transition: 'all 0.2s ease-in-out',
  '&:hover': {
    backgroundColor: '#2563eb',
    boxShadow: '0 4px 6px -1px rgb(37 99 235 / 0.1), 0 2px 4px -2px rgb(37 99 235 / 0.1)',
  }
}));

const PasswordStrengthIndicator = styled(Box)(({ strength }) => ({
  height: '4px',
  borderRadius: '2px',
  backgroundColor:
    strength === 'strong' ? '#22c55e' :
      strength === 'medium' ? '#eab308' :
        strength === 'weak' ? '#ef4444' : '#e2e8f0',
  transition: 'all 0.2s ease-in-out'
}));

const RequirementItem = styled(Box)(({ met }) => ({
  display: 'flex',
  alignItems: 'center',
  gap: '8px',
  color: met ? '#22c55e' : '#94a3b8',
  fontSize: '16px',
  marginBottom: '4px'
}));

const ResetPassword = ({ setShowModal }) => {
  const [oldPassword, setOldPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showOldPassword, setShowOldPassword] = useState(false);
  const [showNewPassword, setShowNewPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const navigate = useNavigate();
  // Password requirements
  const requirements = {
    length: newPassword.length >= 8,
    number: /\d/.test(newPassword),
    special: /[!@#$%^&*]/.test(newPassword),
    capital: /[A-Z]/.test(newPassword)
  };

  // Calculate password strength
  const getPasswordStrength = () => {
    const metRequirements = Object.values(requirements).filter(Boolean).length;
    if (metRequirements === 4) return 'strong';
    if (metRequirements >= 2) return 'medium';
    if (metRequirements >= 1) return 'weak';
    return 'none';
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (newPassword !== confirmPassword) {
      toast.error('Passwords do not match');
      return;
    }

    const EncryptOldPassword = CryptoJS.AES.encrypt(oldPassword, config.PWD_SECRET).toString();
    const EncryptNewPassword = CryptoJS.AES.encrypt(newPassword, config.PWD_SECRET).toString();

    const response = await POST('/api/changepassword', { password: EncryptNewPassword, CurrentPassword: EncryptOldPassword });
    // console.log(response.data);

    if (response.data?.success) {
      toast.success(response.data?.message);
      setShowModal(false);
      return;

    } else if (response.data?.caught) {
      // toast.error(response.data?.message);
      setShowModal(false);
      navigate('/login');
      return;
    } else {
      toast.error(response.data?.message);
    }



    console.log('Password reset submitted');
  };

  return (
    <StyledCard>
      <Typography variant="h5" sx={{
        fontWeight: 600,
        mb: 1,
        color: '#0f172a'
      }}>
        Reset Password
      </Typography>
      <Typography variant="body2" sx={{
        mb: 4,
        color: '#64748b'
      }}>
        Please enter your old password and create a new password
      </Typography>

      <form onSubmit={handleSubmit}>
        <StyledInput
          type={showOldPassword ? 'text' : 'password'}
          placeholder="Current Password"
          value={oldPassword}
          onChange={(e) => setOldPassword(e.target.value)}
          fullWidth
          required
          endAdornment={
            <InputAdornment position="end">
              <IconButton
                onClick={() => setShowOldPassword(!showOldPassword)}
                edge="end"
                sx={{ mr: 1 }}
              >
                {showOldPassword ?
                  <EyeOff size={20} color="#64748b" /> :
                  <Eye size={20} color="#64748b" />
                }
              </IconButton>
            </InputAdornment>
          }
        />

        <StyledInput
          type={showNewPassword ? 'text' : 'password'}
          placeholder="New Password"
          value={newPassword}
          onChange={(e) => setNewPassword(e.target.value)}
          fullWidth
          required
          endAdornment={
            <InputAdornment position="end">
              <IconButton
                onClick={() => setShowNewPassword(!showNewPassword)}
                edge="end"
                sx={{ mr: 1 }}
              >
                {showNewPassword ?
                  <EyeOff size={20} color="#64748b" /> :
                  <Eye size={20} color="#64748b" />
                }
              </IconButton>
            </InputAdornment>
          }
        />

        <Box sx={{ mb: 3 }}>
          <PasswordStrengthIndicator strength={getPasswordStrength()} />
          <Box sx={{ mt: 2 }}>
            <RequirementItem met={requirements.length}>
              {requirements.length ? <Check size={16} /> : <X size={16} />}
              At least 8 characters
            </RequirementItem>
            <RequirementItem met={requirements.number}>
              {requirements.number ? <Check size={16} /> : <X size={16} />}
              Contains a number
            </RequirementItem>
            <RequirementItem met={requirements.special}>
              {requirements.special ? <Check size={16} /> : <X size={16} />}
              Contains a special character
            </RequirementItem>
            <RequirementItem met={requirements.capital}>
              {requirements.capital ? <Check size={16} /> : <X size={16} />}
              Contains a capital letter
            </RequirementItem>
          </Box>
        </Box>

        <StyledInput
          type={showConfirmPassword ? 'text' : 'password'}
          placeholder="Confirm New Password"
          value={confirmPassword}
          onChange={(e) => setConfirmPassword(e.target.value)}
          fullWidth
          required
          endAdornment={
            <InputAdornment position="end">
              <IconButton
                onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                edge="end"
                sx={{ mr: 1 }}
              >
                {showConfirmPassword ?
                  <EyeOff size={20} color="#64748b" /> :
                  <Eye size={20} color="#64748b" />
                }
              </IconButton>
            </InputAdornment>
          }
        />

        <StyledButton
          type="submit"
          variant="contained"
          disabled={
            !oldPassword ||
            !newPassword ||
            !confirmPassword ||
            newPassword !== confirmPassword ||
            getPasswordStrength() !== 'strong'
          }
        >
          Update Password
        </StyledButton>
      </form>
    </StyledCard>
  );
};

export default ResetPassword;

// frontend_angular/src/app/components/reset-password/reset-password.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBarModule, MatSnackBar } from '@angular/material/snack-bar';
import { Router } from '@angular/router';
import * as CryptoJS from 'crypto-js';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-reset-password',
  standalone: true,
  imports: [CommonModule, FormsModule, MatIconModule, MatProgressSpinnerModule, MatSnackBarModule],
  templateUrl: './reset-password.component.html',
  styleUrls: ['./reset-password.component.scss']
})
export class ResetPasswordComponent {
  @Output() closed = new EventEmitter<void>();

  oldPassword = '';
  newPassword = '';
  confirmPassword = '';
  showOldPassword = false;
  showNewPassword = false;
  showConfirmPassword = false;
  isLoading = false;
  errorMessage = '';
  successMessage = '';

  constructor(
    private api: ApiService,
    private auth: AuthService,
    private router: Router,
    private snackBar: MatSnackBar
  ) {}

  private toast(message: string): void {
    this.snackBar.open(message, '', { duration: 2500, horizontalPosition: 'center', verticalPosition: 'bottom' });
  }

  get requirements() {
    return {
      length: this.newPassword.length >= 8,
      number: /\d/.test(this.newPassword),
      special: /[!@#$%^&*]/.test(this.newPassword),
      capital: /[A-Z]/.test(this.newPassword),
    };
  }

  get strength(): string {
    const met = Object.values(this.requirements).filter(Boolean).length;
    if (met === 4) return 'strong';
    if (met >= 2) return 'medium';
    if (met >= 1) return 'weak';
    return 'none';
  }

  get canSubmit(): boolean {
    return (
      !!this.oldPassword &&
      !!this.newPassword &&
      !!this.confirmPassword &&
      this.newPassword === this.confirmPassword &&
      this.strength === 'strong'
    );
  }

  submit(): void {
    if (!this.canSubmit) return;

    if (this.newPassword !== this.confirmPassword) {
      this.errorMessage = 'Passwords do not match.';
      this.toast(this.errorMessage);
      return;
    }

    this.isLoading = true;
    this.errorMessage = '';
    this.successMessage = '';

    const encOld = CryptoJS.AES.encrypt(this.oldPassword, environment.PWD_SECRET).toString();
    const encNew = CryptoJS.AES.encrypt(this.newPassword, environment.PWD_SECRET).toString();

    this.api.post<any>('/api/changepassword', {
      CurrentPassword: encOld,
      password: encNew
    }).subscribe({
      next: (res) => {
        this.isLoading = false;
        if (res?.caught) {
          this.closed.emit();
          this.router.navigate(['/login']);
          return;
        }
        if (res?.success) {
          this.successMessage = res.message || 'Password changed successfully!';
          this.toast(this.successMessage);
          setTimeout(() => this.closed.emit(), 1500);
        } else {
          this.errorMessage = res?.message || 'Failed to change password.';
          this.toast(this.errorMessage);
        }
      },
      error: () => {
        this.isLoading = false;
        this.errorMessage = 'Something went wrong.';
      }
    });
  }

  onOverlayClick(event: Event): void {
    if ((event.target as HTMLElement).classList.contains('reset-overlay')) {
      this.closed.emit();
    }
  }
}

<div class="reset-overlay" (click)="onOverlayClick($event)">
  <div class="reset-card" (click)="$event.stopPropagation()">
    <button class="close-btn" (click)="closed.emit()">
      <mat-icon>close</mat-icon>
    </button>

    <h2 class="step-title">Reset Password</h2>
    <p class="step-subtitle">Please enter your old password and create a new password</p>

    @if (errorMessage) {
      <div class="error-msg">
        <mat-icon>error_outline</mat-icon>
        <span>{{ errorMessage }}</span>
      </div>
    }
    @if (successMessage) {
      <div class="success-msg">
        <mat-icon>check_circle</mat-icon>
        <span>{{ successMessage }}</span>
      </div>
    }

    <form (ngSubmit)="submit()">
      <!-- Old Password -->
      <div class="input-wrapper">
        <mat-icon class="field-icon">key</mat-icon>
        <input
          [type]="showOldPassword ? 'text' : 'password'"
          placeholder="Current Password"
          [(ngModel)]="oldPassword"
          name="oldPassword"
          required
          class="custom-input"
        />
        <button type="button" class="toggle-btn" (click)="showOldPassword = !showOldPassword">
          <mat-icon>{{ showOldPassword ? 'visibility' : 'visibility_off' }}</mat-icon>
        </button>
      </div>

      <!-- New Password -->
      <div class="input-wrapper">
        <mat-icon class="field-icon">key</mat-icon>
        <input
          [type]="showNewPassword ? 'text' : 'password'"
          placeholder="New Password"
          [(ngModel)]="newPassword"
          name="newPassword"
          required
          class="custom-input"
        />
        <button type="button" class="toggle-btn" (click)="showNewPassword = !showNewPassword">
          <mat-icon>{{ showNewPassword ? 'visibility' : 'visibility_off' }}</mat-icon>
        </button>
      </div>

      <!-- Strength Bar -->
      @if (newPassword) {
        <div class="strength-section">
          <div class="strength-bar">
            <div
              class="strength-fill"
              [class.weak]="strength === 'weak'"
              [class.medium]="strength === 'medium'"
              [class.strong]="strength === 'strong'"
            ></div>
          </div>
          <div class="requirements">
            <div class="req" [class.met]="requirements.length">
              <mat-icon>{{ requirements.length ? 'check' : 'close' }}</mat-icon>
              At least 8 characters
            </div>
            <div class="req" [class.met]="requirements.number">
              <mat-icon>{{ requirements.number ? 'check' : 'close' }}</mat-icon>
              Contains a number
            </div>
            <div class="req" [class.met]="requirements.special">
              <mat-icon>{{ requirements.special ? 'check' : 'close' }}</mat-icon>
              Contains a special character
            </div>
            <div class="req" [class.met]="requirements.capital">
              <mat-icon>{{ requirements.capital ? 'check' : 'close' }}</mat-icon>
              Contains a capital letter
            </div>
          </div>
        </div>
      }

      <!-- Confirm Password -->
      <div class="input-wrapper">
        <mat-icon class="field-icon">key</mat-icon>
        <input
          [type]="showConfirmPassword ? 'text' : 'password'"
          placeholder="Confirm New Password"
          [(ngModel)]="confirmPassword"
          name="confirmPassword"
          required
          class="custom-input"
        />
        <button type="button" class="toggle-btn" (click)="showConfirmPassword = !showConfirmPassword">
          <mat-icon>{{ showConfirmPassword ? 'visibility' : 'visibility_off' }}</mat-icon>
        </button>
      </div>

      @if (confirmPassword && newPassword !== confirmPassword) {
        <div class="mismatch-msg">Passwords do not match</div>
      }

      <button type="submit" class="submit-btn" [disabled]="isLoading || !canSubmit">
        @if (isLoading) {
          <mat-spinner diameter="22" class="btn-spinner"></mat-spinner>
        } @else {
          Update Password
        }
      </button>
    </form>
  </div>
</div>
